# Generated by Django 4.2.20 on 2025-07-04 02:53

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionOSM',
            fields=[
                ('osm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_level', models.CharField(blank=True, max_length=10, null=True)),
                ('way_area', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(db_column='way', srid=4326)),
            ],
            options={
                'db_table': 'planet_osm_polygon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('total_reviews', models.IntegerField(blank=True, null=True)),
                ('precio', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('horario_texto', models.TextField(blank=True, null=True)),
                ('abierto_ahora', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('photo_reference', models.CharField(blank=True, max_length=1000, null=True)),
                ('imagen', models.ImageField(blank=True, max_length=500, null=True, upload_to='portadas_lugares/')),
                ('reviews', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZonaCubierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('poligono', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes_medellin/')),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='explorer.places')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.places')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'lugar')},
            },
        ),
    ]
