# Generated by Django 5.2.4 on 2025-07-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='imagen',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to='portadas_lugares/'),
        ),
    ]
