# Generated by Django 5.2.4 on 2025-07-16 21:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_alter_foto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='accepts_cash_only',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='accepts_credit_cards',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='accepts_debit_cards',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='accepts_nfc',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='allows_dogs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='areas_google_api',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='places',
            name='delivery',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='dine_in',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='directions_uri',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='good_for_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='good_for_groups',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='google_api_json',
            field=models.FileField(blank=True, null=True, upload_to='api_json/'),
        ),
        migrations.AddField(
            model_name='places',
            name='google_maps_uri',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='horario_json',
            field=models.JSONField(blank=True, help_text='Horario completo del lugar', null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='live_music',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='menu_for_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='outdoor_seating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_beer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_breakfast',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_brunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_cocktails',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_coffee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_dessert',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_dinner',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_lunch',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='serves_wine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='takeout',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='places',
            name='wheelchair_accessible_entrance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='wheelchair_accessible_parking',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='wheelchair_accessible_restroom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='wheelchair_accessible_seating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='places',
            name='sitio_web',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
