# Generated by Django 5.2.4 on 2025-01-19 21:38

import pgvector.django
from django.db import migrations, models
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_places_accepts_cash_only_places_accepts_credit_cards_and_more'),
    ]

    operations = [
        # Habilitar la extensión pgvector
        CreateExtension('vector'),
        
        migrations.AddField(
            model_name='places',
            name='embedding',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='places',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
