# Generated by Django 5.2.4 on 2025-07-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_places_embedding_places_summary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorito',
        ),
    ]
