# Generated by Django 5.2.4 on 2025-07-17 02:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_convertir_srid_3857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionosm',
            name='geom',
        ),
        migrations.AddField(
            model_name='regionosm',
            name='geom_3857',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geometría en Web Mercator', null=True, srid=3857),
        ),
        migrations.AddField(
            model_name='regionosm',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Geometría en WGS84 (lat/lng)', null=True, srid=4326),
        ),
    ]
