# Generated by Django 5.2.4 on 2025-07-18 00:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_remove_regionosm_geom_regionosm_geom_3857_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initialgrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
