# Generated by Django 5.2.4 on 2025-07-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_initialgrid'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialgrid',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='initialgrid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='places',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
