# Generated by Django 5.2.4 on 2025-07-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_initialgrid_is_processed_alter_initialgrid_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialgrid',
            name='is_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
