# Generated by Django 5.2.4 on 2025-07-22 19:43

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_alter_places_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['-rating', 'nombre']},
        ),
        migrations.AlterField(
            model_name='foto',
            name='imagen',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='initialgrid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='initialgrid',
            name='points',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='places',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='zonacubierta',
            name='poligono',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['nombre'], name='nombre_idx'),
        ),
        migrations.AddIndex(
            model_name='places',
            index=models.Index(fields=['tipo'], name='tipo_idx'),
        ),
        migrations.AddIndex(
            model_name='places',
            index=django.contrib.postgres.indexes.GistIndex(fields=['ubicacion'], name='ubicacion_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='regionosm',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom_4326'], name='region_geom_4326_gist'),
        ),
        migrations.AddIndex(
            model_name='regionosm',
            index=django.contrib.postgres.indexes.GistIndex(fields=['geom_3857'], name='region_geom_3857_gist'),
        ),
    ]
