# Generated by Django 5.2.4 on 2025-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0014_alter_places_options_alter_foto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='es_destacado',
            field=models.BooleanField(default=False, help_text='Lugares con mejor rating y más reviews'),
        ),
        migrations.AddField(
            model_name='places',
            name='es_exclusivo',
            field=models.BooleanField(default=False, help_text='Lugares especiales o VIP'),
        ),
        migrations.AddField(
            model_name='places',
            name='tiene_fotos',
            field=models.BooleanField(default=False, help_text='Indica si el lugar tiene fotos asociadas'),
        ),
    ]
