# Generated by Django 5.2.4 on 2025-07-22 20:36

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_tag_taggedplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Lista de etiquetas separadas por comas', through='explorer.TaggedPlace', to='explorer.Tag', verbose_name='Etiquetas'),
        ),
    ]
