# Generated by Django 5.2.4 on 2025-07-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_places_show_in_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionosm',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable generada automáticamente', max_length=255, null=True, unique=True),
        ),
    ]
