# Generated by Django 5.2.4 on 2025-07-30 00:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0019_agregar_slug_regiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico del suscriptor', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('nombre', models.CharField(blank=True, help_text='Nombre del suscriptor (opcional)', max_length=100)),
                ('fecha_suscripcion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de suscripción')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la suscripción está activa')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se suscribió', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent del navegador')),
                ('confirmado', models.BooleanField(default=False, help_text='Indica si el email ha sido confirmado')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha y hora de confirmación del email', null=True)),
                ('token_confirmacion', models.CharField(blank=True, help_text='Token para confirmar la suscripción', max_length=64)),
                ('fuente', models.CharField(default='website', help_text='Origen de la suscripción (website, landing, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'Suscripción Newsletter',
                'verbose_name_plural': 'Suscripciones Newsletter',
                'ordering': ['-fecha_suscripcion'],
                'indexes': [models.Index(fields=['email'], name='explorer_ne_email_724397_idx'), models.Index(fields=['activo', 'confirmado'], name='explorer_ne_activo_41f30a_idx'), models.Index(fields=['fecha_suscripcion'], name='explorer_ne_fecha_s_22dbef_idx')],
            },
        ),
    ]
