# Generated by Django 5.2.4 on 2025-08-20 18:29

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0020_newslettersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
