# Generated by Django 5.2.4 on 2025-12-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0022_places_imagenes_optimizadas_foto_variantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['-weighted_rating', '-rating', 'nombre']},
        ),
        migrations.AddField(
            model_name='places',
            name='weighted_rating',
            field=models.FloatField(blank=True, db_index=True, help_text='Rating ponderado usando Bayesian Average (considera cantidad de reviews)', null=True),
        ),
    ]
