# Generated by Django 5.2.4 on 2026-02-10 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0023_add_weighted_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ej: Los 10 Mejores Bares en El Poblado', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Se genera automáticamente del título', max_length=220, unique=True)),
                ('descripcion', models.TextField(help_text='Tu intro personal para la guía')),
                ('imagen_cover', models.URLField(blank=True, help_text='URL de imagen de portada (opcional). Si vacío, usa la foto del lugar #1', max_length=500)),
                ('categoria', models.CharField(choices=[('sector', 'Por Zona'), ('audiencia', 'Por Audiencia'), ('actividad', 'Por Actividad'), ('daytrip', 'Excursión / Day Trip'), ('gastronomia', 'Gastronomía')], db_index=True, default='sector', max_length=30)),
                ('publicado', models.BooleanField(db_index=True, default=False, help_text='Solo las guías publicadas aparecen en el sitio')),
                ('orden', models.IntegerField(default=0, help_text='Orden en el índice de guías (menor = primero)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('zona', models.ForeignKey(blank=True, help_text='Zona asociada (opcional, para filtrar por sector)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='explorer.regionosm')),
            ],
            options={
                'verbose_name': 'Guía Curada',
                'verbose_name_plural': 'Guías Curadas',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CuratedGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField(default=1, help_text='Posición en el ranking (1 = el mejor)')),
                ('comentario', models.TextField(blank=True, help_text='Tu recomendación personal: qué pedir, cuándo ir, tips...')),
                ('destacado', models.CharField(blank=True, help_text="Badge corto: 'Mi favorito', 'Mejor terraza', 'Hidden gem'", max_length=50)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='explorer.curatedguide')),
                ('lugar', models.ForeignKey(help_text='Busca el lugar por nombre', on_delete=django.db.models.deletion.CASCADE, related_name='en_guias', to='explorer.places')),
            ],
            options={
                'verbose_name': 'Lugar en Guía',
                'verbose_name_plural': 'Lugares en Guía',
                'ordering': ['posicion'],
                'unique_together': {('guia', 'lugar'), ('guia', 'posicion')},
            },
        ),
    ]
