# Generated by Django 5.2.4 on 2026-02-10 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0024_add_curated_guides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curatedguide',
            name='zona',
            field=models.ForeignKey(blank=True, help_text='Zona específica (opcional). Dejar vacío = Medellín en general', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias', to='explorer.regionosm'),
        ),
    ]
