# Generated by Django 5.2.4 on 2026-02-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0025_update_zona_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedguide',
            name='descripcion_en',
            field=models.TextField(blank=True, help_text='Description in English (dejar vacío = usa español)'),
        ),
        migrations.AddField(
            model_name='curatedguide',
            name='titulo_en',
            field=models.CharField(blank=True, help_text='Title in English (dejar vacío = usa español)', max_length=200),
        ),
        migrations.AddField(
            model_name='curatedguideitem',
            name='comentario_en',
            field=models.TextField(blank=True, help_text='Your recommendation in English (dejar vacío = usa español)'),
        ),
        migrations.AddField(
            model_name='curatedguideitem',
            name='destacado_en',
            field=models.CharField(blank=True, help_text="Badge in English: 'My favorite', 'Best terrace'", max_length=50),
        ),
        migrations.AlterField(
            model_name='curatedguide',
            name='descripcion',
            field=models.TextField(help_text='Descripción en español'),
        ),
        migrations.AlterField(
            model_name='curatedguide',
            name='titulo',
            field=models.CharField(help_text='Título en español', max_length=200),
        ),
        migrations.AlterField(
            model_name='curatedguideitem',
            name='comentario',
            field=models.TextField(blank=True, help_text='Tu recomendación en español'),
        ),
        migrations.AlterField(
            model_name='curatedguideitem',
            name='destacado',
            field=models.CharField(blank=True, help_text="Badge en español: 'Mi favorito', 'Mejor terraza'", max_length=50),
        ),
    ]
