# Generated by Django 5.2.4 on 2026-02-13 00:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0026_add_english_translations_guides'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('nombre', models.CharField(blank=True, help_text='Nombre básico de la API', max_length=255)),
                ('tipos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Tipos de Google', size=None)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('failed', 'Falló'), ('skipped', 'Descartado')], db_index=True, default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('descubierto_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lugar Pendiente',
                'verbose_name_plural': 'Lugares Pendientes',
                'ordering': ['-descubierto_en'],
            },
        ),
    ]
